services:
  meilisearch:
    image: getmeili/meilisearch:v1.25
    container_name: meilisearch
    restart: unless-stopped
    ports:
      - "127.0.0.1:7700:7700"
    volumes:
      - ./data/meili_data:/meili_data
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    mem_limit: 6g
    command: ["meilisearch", "--http-addr", "[::]:7700", "--experimental-contains-filter", "--max-indexing-memory", "5Gb", "--experimental-dumpless-upgrade"]
